Repository R2NorthstarTools/FlightCore, pull requests merged in 2023-03, with the labels that each got.

#191 build: Keep line tables in release builds
  src-tauri/Cargo.toml
Labels: high priority

#217 refactor: Fix PR downloads permission issue
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/github/pull_requests.rs
Labels: bug

#211 fix: Add error handling if default EA App path
  src-tauri/src/lib.rs
Labels: bug

#203 Add buttons to download PRs
  src-tauri/src/github/pull_requests.rs
  src-tauri/src/main.rs
  src-vue/src/components/PullRequestsSelector.vue
  src-vue/src/plugins/modules/pull_requests.ts
Labels: enhancement

#226 fix: Address clippy errors in glibc parsing code
  src-tauri/src/lib.rs
  src-tauri/src/platform_specific/linux.rs
Labels: enhancement

#230 fix: Remove unnecessary `.to_string()`
  src-tauri/src/lib.rs
  src-tauri/src/platform_specific/windows.rs
Labels: enhancement

#229 fix: Address clippy warnings regarding format!()
  src-tauri/src/lib.rs
Labels: enhancement

#231 fix: Remove unnecessary borrows
  src-tauri/src/lib.rs
Labels: enhancement

#232 fix: Adjust code for single iteration loop
  src-tauri/src/lib.rs
Labels: enhancement

#236 refactor: Replace all `println!()` with log statements
  src-tauri/src/github/pull_requests.rs
  src-tauri/src/github/release_notes.rs
  src-tauri/src/lib.rs
  src-tauri/src/main.rs
  src-tauri/src/mod_management/mod.rs
  src-tauri/src/platform_specific/windows.rs
  src-tauri/src/thunderstore/mod.rs
Labels: enhancement

#242 fix: Remove redundant string conversions
  src-tauri/src/github/pull_requests.rs
  src-tauri/src/main.rs
  src-tauri/src/mod_management/mod.rs
Labels: enhancement

#227 fix: Address regression around persistent store
  docs/DEVELOPMENT.md
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/main.rs
  src-vue/package-lock.json
  src-vue/package.json
  src-vue/src/plugins/store.ts
  src-vue/src/views/SettingsView.vue
Labels: bug

#188 feat: Generate FlightCore release notes
  src-tauri/bindings/Tag.ts
  src-tauri/bindings/TagWrapper.ts
  src-tauri/src/constants.rs
  src-tauri/src/github/mod.rs
  src-tauri/src/main.rs
  src-vue/src/views/DeveloperView.vue
Labels: help wanted

#244 fix: Replace `<=0` with `.is_empty()`
  src-tauri/src/mod_management/mod.rs
  src-tauri/src/repair_and_verify/mod.rs
Labels: enhancement

#182 feat: i18n
  docs/DEVELOPMENT.md
  src-vue/package-lock.json
  src-vue/package.json
  src-vue/src/App.vue
  src-vue/src/components/LanguageSelector.vue
  src-vue/src/components/ModsMenu.vue
  src-vue/src/components/PlayButton.vue
  src-vue/src/components/ThunderstoreModCard.vue
  src-vue/src/i18n/lang/en.ts
  src-vue/src/i18n/lang/fr.ts
  src-vue/src/main.ts
  src-vue/src/plugins/store.ts
  src-vue/src/utils/SortOptions.d.ts
  src-vue/src/views/PlayView.vue
  src-vue/src/views/RepairView.vue
  src-vue/src/views/SettingsView.vue
  src-vue/src/views/mods/LocalModsView.vue
  src-vue/src/views/mods/ThunderstoreModsView.vue
Labels: enhancement

#240 docs: Expand on the Setup (build) instructions
  docs/DEVELOPMENT.md
Labels: documentation

#248 docs: Explanation on expanding language selector
  docs/DEVELOPMENT.md
Labels: documentation

#247 refactor: Style
  src-vue/src/App.vue
  src-vue/src/plugins/store.ts
  src-vue/src/style.css
  src-vue/src/views/SettingsView.vue
  src-vue/src/views/mods/LocalModsView.vue
  src-vue/src/views/mods/ThunderstoreModsView.vue
Labels: enhancement
