Repository R2NorthstarTools/FlightCore, pull requests merged in 2023-04, with the labels that each got.

#246 fix: Another set of various clippy fixes
  src-tauri/src/github/mod.rs
  src-tauri/src/lib.rs
  src-tauri/src/repair_and_verify/mod.rs
Labels: enhancement

#256 build: Generate release draft on tag
  .github/workflows/release.yml
Labels: enhancement

#249 feat: Initial German translation
  src-vue/src/components/LanguageSelector.vue
  src-vue/src/i18n/lang/de.json
  src-vue/src/main.ts
Labels: enhancement

#178 feat: Add ability to launch via Steam to DevView
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/constants.rs
  src-tauri/src/lib.rs
  src-tauri/src/main.rs
  src-vue/src/plugins/store.ts
  src-vue/src/views/DeveloperView.vue
Labels: enhancement

#257 build: Use `npm clean-install`
  .github/workflows/push-test.yml
  .github/workflows/release.yml
Labels: enhancement

#255 fix: Change enum value casing
  src-tauri/bindings/PullRequestType.ts
  src-tauri/src/github/pull_requests.rs
  src-vue/src/components/PullRequestsSelector.vue
  src-vue/src/plugins/modules/pull_requests.ts
Labels: enhancement

#200 feat: Show download progress for installing Northstar
  src-tauri/bindings/InstallProgress.ts
  src-tauri/bindings/InstallState.ts
  src-tauri/src/lib.rs
  src-tauri/src/main.rs
  src-vue/src/components/InstallProgressBar.vue
  src-vue/src/components/PlayButton.vue
  src-vue/src/i18n/lang/en.json
  src-vue/src/views/PlayView.vue
  src-vue/src/views/RepairView.vue
Labels: enhancement

#270 fix: Fix incorrect is_empty check
  src-tauri/src/mod_management/mod.rs
Labels: bug

#271 fix: Repair view add missing i18n
  src-vue/src/i18n/lang/de.json
  src-vue/src/i18n/lang/en.json
  src-vue/src/i18n/lang/fr.json
  src-vue/src/views/RepairView.vue
Labels: bug

#272 build: Only upload platform relevant artifacts
  .github/workflows/push-test.yml
Labels: enhancement

#273 build: Additionally upload binaries separately from CI
  .github/workflows/push-test.yml
Labels: enhancement

#275 docs: Add docs for DevView
  README.md
  docs/DEV-TOOLS.md
  docs/assets/dev-view-screenshot.png
Labels: documentation

#276 refactor: Reorder DevView elements
  src-vue/src/views/DeveloperView.vue
Labels: enhancement

#286 docs: Add troubleshooting section
  docs/FAQ.md
  docs/TROUBLESHOOTING.md
  docs/assets/webview2-download-screenshot.png
Labels: documentation
